# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:

#     # deploy_django:
#     #     name: Deploy Django
#     #     runs-on: ubuntu-latest
#     #     steps:
#     #         - name: Deploy to server
#     #           if: ${{ !env.ACT }}
#     #           uses: appleboy/ssh-action@master
#     #           with:
#     #             host: ${{ secrets.SERVER_HOST }}
#     #             username: ${{ secrets.SERVER_USER }}
#     #             password: ${{ secrets.SERVER_PASSWORD }}
#     #             port: ${{ secrets.SERVER_PORT }}
#     #             script: |
#     #                 cd ${{ secrets.PROJECT_PATH }}
#     #                 git pull ${{ secrets.REPO_URL }}
#     #                 docker-compose down
#     #                 docker-compose up --build -d
